version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-audio
    ports:
      - "8428:8428"
    volumes:
      - ./data:/data
      - ./.env:/app/.env  # Монтируем .env в контейнер
      - ./cookies:/cookies # Монтируем cookies директорию, если нужно
    networks:
      - default
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8428"]

networks:
  default: